//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: LoginProtos.proto
namespace Freecon.Core.Networking.Models.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequestProto")]
  public partial class LoginRequestProto : global::ProtoBuf.IExtensible
  {
    public LoginRequestProto() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _password; }
      set { _password = value; }
    }
    private HandshakeToken _Token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HandshakeToken Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReponseProto")]
  public partial class LoginReponseProto : global::ProtoBuf.IExtensible
  {
    public LoginReponseProto() {}
    
    private int _ResponseCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ResponseCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ResponseCode
    {
      get { return _ResponseCode; }
      set { _ResponseCode = value; }
    }
    private string _AuthToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AuthToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AuthToken
    {
      get { return _AuthToken; }
      set { _AuthToken = value; }
    }
    private byte[] _Meta;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Meta
    {
      get { return _Meta?? null; }
      set { _Meta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MetaSpecified
    {
      get { return this._Meta != null; }
      set { if (value == (this._Meta== null)) this._Meta = value ? this.Meta : (byte[])null; }
    }
    private bool ShouldSerializeMeta() { return MetaSpecified; }
    private void ResetMeta() { MetaSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectionRequestProto")]
  public partial class ConnectionRequestProto : global::ProtoBuf.IExtensible
  {
    public ConnectionRequestProto() {}
    
    private string _ClientVersion;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ClientVersion
    {
      get { return _ClientVersion?? ""; }
      set { _ClientVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ClientVersionSpecified
    {
      get { return this._ClientVersion != null; }
      set { if (value == (this._ClientVersion== null)) this._ClientVersion = value ? this.ClientVersion : (string)null; }
    }
    private bool ShouldSerializeClientVersion() { return ClientVersionSpecified; }
    private void ResetClientVersion() { ClientVersionSpecified = false; }
    
    private byte[] _Meta;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Meta
    {
      get { return _Meta?? null; }
      set { _Meta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MetaSpecified
    {
      get { return this._Meta != null; }
      set { if (value == (this._Meta== null)) this._Meta = value ? this.Meta : (byte[])null; }
    }
    private bool ShouldSerializeMeta() { return MetaSpecified; }
    private void ResetMeta() { MetaSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectionResponseProto")]
  public partial class ConnectionResponseProto : global::ProtoBuf.IExtensible
  {
    public ConnectionResponseProto() {}
    
    private int _ResponseCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ResponseCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ResponseCode
    {
      get { return _ResponseCode; }
      set { _ResponseCode = value; }
    }
    private string _ResponseToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ResponseToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ResponseToken
    {
      get { return _ResponseToken?? ""; }
      set { _ResponseToken = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ResponseTokenSpecified
    {
      get { return this._ResponseToken != null; }
      set { if (value == (this._ResponseToken== null)) this._ResponseToken = value ? this.ResponseToken : (string)null; }
    }
    private bool ShouldSerializeResponseToken() { return ResponseTokenSpecified; }
    private void ResetResponseToken() { ResponseTokenSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandshakeToken")]
  public partial class HandshakeToken : global::ProtoBuf.IExtensible
  {
    public HandshakeToken() {}
    
    private string _ResponseToken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ResponseToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ResponseToken
    {
      get { return _ResponseToken; }
      set { _ResponseToken = value; }
    }
    private byte[] _Meta;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Meta
    {
      get { return _Meta?? null; }
      set { _Meta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MetaSpecified
    {
      get { return this._Meta != null; }
      set { if (value == (this._Meta== null)) this._Meta = value ? this.Meta : (byte[])null; }
    }
    private bool ShouldSerializeMeta() { return MetaSpecified; }
    private void ResetMeta() { MetaSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}