//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: MessageContainerProto.proto
namespace Freecon.Core.Networking.Models.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageContainerProto")]
  public partial class MessageContainerProto : global::ProtoBuf.IExtensible
  {
    public MessageContainerProto() {}
    
    private uint _PayloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PayloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PayloadType
    {
      get { return _PayloadType; }
      set { _PayloadType = value; }
    }
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}